project:
  type: website

website:
  title: "Global Digital Economy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: insights.qmd
        text: Insights
      - sources.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



